# Generated by Django 6.0.2 on 2026-05-06 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('expertise', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OnlineContent',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'online_content',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('isbn_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'textbook',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.IntegerField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'university',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('course', models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.student')),
            ],
            options={
                'db_table': 'evaluation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('instructor_id', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Instructor', 'Instructor'), ('Student', 'Student'), ('Analyst', 'Analyst')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('content', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.onlinecontent')),
            ],
            options={
                'db_table': 'course_content',
                'managed': True,
                'unique_together': {('course', 'content')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('instructor', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.instructor')),
            ],
            options={
                'db_table': 'course_instructor',
                'managed': True,
                'unique_together': {('course', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='CourseTextbook',
            fields=[
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('isbn_number', models.ForeignKey(db_column='isbn_number', on_delete=django.db.models.deletion.DO_NOTHING, to='core.textbook')),
            ],
            options={
                'db_table': 'course_textbook',
                'managed': True,
                'unique_together': {('course', 'isbn_number')},
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.topic')),
            ],
            options={
                'db_table': 'course_topic',
                'managed': True,
                'unique_together': {('course', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CourseUniversity',
            fields=[
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.course')),
                ('university', models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.university')),
            ],
            options={
                'db_table': 'course_university',
                'managed': True,
                'unique_together': {('course', 'university')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.student')),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
            ],
            options={
                'db_table': 'enrollment',
                'managed': True,
                'unique_together': {('student', 'course')},
            },
        ),
    ]
