# Generated by Django 6.0.2 on 2026-05-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='coursetextbook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='courseuniversity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='core.onlinecontent'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='coursetextbook',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='coursetextbook',
            name='isbn_number',
            field=models.ForeignKey(db_column='isbn_number', on_delete=django.db.models.deletion.CASCADE, to='core.textbook'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='topic',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='university',
            field=models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
